/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/kv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["handle_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/kv/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["handle_get"];
    put: operations["handle_put"];
    post?: never;
    delete: operations["handle_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/kv/{key}/incr": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["handle_incr"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error: string;
      message: string;
    };
    IncrResponse: {
      /** Format: int64 */
      value: number;
    };
    KeyItem: {
      name: string;
    };
    ListResponse: {
      complete: boolean;
      cursor?: string | null;
      keys: components["schemas"]["KeyItem"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  handle_list: {
    parameters: {
      query?: {
        /** @description Namespace 0-15, default 0 */
        ns?: number;
        /** @description Filter keys by prefix */
        prefix?: string;
        /** @description Pagination cursor from a previous response */
        cursor?: string;
        /** @description Max keys to return (default 100, max 1000) */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Page of keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListResponse"];
        };
      };
    };
  };
  handle_get: {
    parameters: {
      query?: {
        /** @description Namespace 0-15, default 0 */
        ns?: number;
      };
      header?: never;
      path: {
        /** @description Key to retrieve */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Value bytes */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": unknown;
        };
      };
      /** @description Key not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  handle_put: {
    parameters: {
      query?: {
        /** @description Namespace 0-15, default 0 */
        ns?: number;
        /** @description Set only if key does not exist (nx=1) */
        nx?: number;
        /** @description Set only if key already exists (xx=1) */
        xx?: number;
        /** @description TTL seconds (overridden by X-KV-TTL header) */
        ttl?: number;
      };
      header?: {
        /** @description Set only if current revision matches */
        "If-Match"?: number | null;
        /** @description Preserve existing TTL (incompatible with TTL options) */
        "X-KV-KeepTTL"?: string | null;
        /** @description Return old value atomically (incompatible with conditional writes) */
        "X-KV-Return-Old"?: string | null;
      };
      path: {
        /** @description Key to set */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/octet-stream": unknown;
      };
    };
    responses: {
      /** @description Old value (when X-KV-Return-Old is set and key existed) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": unknown;
        };
      };
      /** @description Stored */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conflicting options */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict (NX/XX or revision mismatch) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  handle_delete: {
    parameters: {
      query?: {
        /** @description Namespace 0-15, default 0 */
        ns?: number;
      };
      header?: {
        /** @description Delete only if current revision matches */
        "If-Match"?: number | null;
      };
      path: {
        /** @description Key to delete */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted (or did not exist) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Revision mismatch */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  handle_incr: {
    parameters: {
      query?: {
        /** @description Namespace 0-15, default 0 */
        ns?: number;
        /** @description Increment delta (default 1) */
        delta?: number;
      };
      header?: never;
      path: {
        /** @description Counter key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description New counter value */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncrResponse"];
        };
      };
      /** @description Stored value is not an integer or overflowed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
